name: SSH_deploy_k8s

on:
  workflow_dispatch: # Срабатывает при запуске вручную из интерфейса GitHub Actions
# on:
#   push:
#     branches:
#       - main # Срабатывает при коммите в ветку main

env:
  SOURCE     : "./" # откуда  
  TARGET     : "~/docker_k8s" # куда на удаленном сервере

jobs:
  deploy_to_ssh:
    runs-on: ubuntu-latest # Определяет ОС на которой будет выполняться деплоймент
    
    steps:
      - name: -------Start-CD-----------
        run: echo "Start CD message" # Выводит стартовое сообщение в логи

      - name: GitHub clone code
        uses: actions/checkout@v3 # Клонирует репозиторий, на котором запущен деплоймент

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main # Запускает экшен для деплоя кода по SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }} # Приватный SSH-ключ для подключения к серверу
          ARGS           : "-rlgoDzvc -i --delete" # Параметры для rsync, используемого для копирования файлов
          SOURCE         : ${{ env.SOURCE }} # откуда  
          REMOTE_HOST    : ${{ secrets.REMOTE_HOST }} # IP-адрес или доменное имя сервера
          REMOTE_USER    : ${{ secrets.REMOTE_USER }} # Имя пользователя для подключения к серверу
          TARGET         : ${{ env.TARGET }} # куда на удаленном сервере
          SCRIPT_BEFORE: |
            ls -la # Вывод списка файлов и папок в логи перед деплоем
          SCRIPT_AFTER: |
            cd ${{ env.TARGET }} # Переход в локальную папку с кодом
            ls -la # Вывод списка файлов и папок в логи после деплоя
      - name: -------Finish-CD-----------
        run: |
          echo "🍏 This job's status is ${{ job.status }}." # Выводит сообщение о завершении деплоймента в логи с указанием статуса работы джобы (success/failure)
